include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    prefer_function_declarations_over_variables: true
    unnecessary_new: true
    await_only_futures: true
    curly_braces_in_flow_control_structures: true
    lines_longer_than_80_chars: false

# Note: 'dart format' usually takes line length from CLI args, but some tools check here.