// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApqlGU5-R2TfHjxGzRijPfgvzNXPJDh7I',
    appId: '1:633603071053:web:4dfdfc620b34c1d64b1004',
    messagingSenderId: '633603071053',
    projectId: 'memverse-809c7',
    authDomain: 'memverse-809c7.firebaseapp.com',
    databaseURL: 'https://memverse-809c7.firebaseio.com',
    storageBucket: 'memverse-809c7.firebasestorage.app',
    measurementId: 'G-RELXT35950',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwEtFxCNr5Zc-IUDPwAG3a71N8qDW9OOU',
    appId: '1:633603071053:android:c15da9565fc5b468',
    messagingSenderId: '633603071053',
    projectId: 'memverse-809c7',
    databaseURL: 'https://memverse-809c7.firebaseio.com',
    storageBucket: 'memverse-809c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIYPMKAOX-yeSKO2gr93me-q_Mqg9jnU',
    appId: '1:633603071053:ios:f9cf5dc5eb1e85cf4b1004',
    messagingSenderId: '633603071053',
    projectId: 'memverse-809c7',
    databaseURL: 'https://memverse-809c7.firebaseio.com',
    storageBucket: 'memverse-809c7.firebasestorage.app',
    androidClientId: '633603071053-lbvakvfcfqd9dih67cq0o39ceigh0rif.apps.googleusercontent.com',
    iosBundleId: 'com.spiritflightapps.memverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvIYPMKAOX-yeSKO2gr93me-q_Mqg9jnU',
    appId: '1:633603071053:ios:f9cf5dc5eb1e85cf4b1004',
    messagingSenderId: '633603071053',
    projectId: 'memverse-809c7',
    databaseURL: 'https://memverse-809c7.firebaseio.com',
    storageBucket: 'memverse-809c7.firebasestorage.app',
    androidClientId: '633603071053-lbvakvfcfqd9dih67cq0o39ceigh0rif.apps.googleusercontent.com',
    iosBundleId: 'com.spiritflightapps.memverse',
  );
}
