// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return AndroidFirebaseOptions.currentPlatform;
      case TargetPlatform.iOS:
        return IosFirebaseOptions.currentPlatform;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this file by running the FlutterFire CLI again.',
        );
      case TargetPlatform.web:
        return WebFirebaseOptions.currentPlatform;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this file by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this file by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}

class AndroidFirebaseOptions implements FirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyCwEtFxCNr5Zc-IUDPwAG3a71N8qDW9OOU',
    appId: '1:633603071053:android:c15da9565fc5b468',
    messagingSenderId: '633603071053',
    projectId: 'memverse-809c7',
    databaseURL: 'https://memverse-809c7.firebaseio.com',
    storageBucket: 'memverse-809c7.firebasestorage.app',
  );

  @override
  final String apiKey;

  @override
  final String appId;

  @override
  final String? appGroupId;

  @override
  final String? bundleId;

  @override
  final String? clientId;

  @override
  final String? databaseURL;

  @override
  final String? deepLinkURLScheme;

  @override
  final String? gaTrackingId;

  @override
  final String messagingSenderId;

  @override
  final String projectId;

  @override
  final String? reverseClientId;

  @override
  final String? storageBucket;

  @override
  final String? trackingId;

  AndroidFirebaseOptions({
    required this.apiKey,
    required this.appId,
    this.appGroupId,
    this.bundleId,
    this.clientId,
    this.databaseURL,
    this.deepLinkURLScheme,
    this.gaTrackingId,
    required this.messagingSenderId,
    required this.projectId,
    this.reverseClientId,
    this.storageBucket,
    this.trackingId,
  });
}

class IosFirebaseOptions implements FirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyBvIYPMKAOX-yeSKO2gr93me-q_Mqg9jnU',
    appId: '1:633603071053:ios:beb680553b8de93b4b1004',
    messagingSenderId: '633603071053',
    projectId: 'memverse-809c7',
    databaseURL: 'https://memverse-809c7.firebaseio.com',
    storageBucket: 'memverse-809c7.firebasestorage.app',
    androidClientId: '633603071053-lbvakvfcfqd9dih67cq0o39ceigh0rif.apps.googleusercontent.com',
    iosClientId: '633603071053-1o341fl8ljmhnt17u19keqrbiv03qhap.apps.googleusercontent.com',
  );

  @override
  final String apiKey;

  @override
  final String appId;

  @override
  final String? appGroupId;

  @override
  final String? bundleId;

  @override
  final String? clientId;

  @override
  final String? databaseURL;

  @override
  final String? deepLinkURLScheme;

  @override
  final String? gaTrackingId;

  @override
  final String messagingSenderId;

  @override
  final String projectId;

  @override
  final String? reverseClientId;

  @override
  final String? storageBucket;

  @override
  final String? trackingId;

  @override
  final String? androidClientId;

  @override
  final String? iosClientId;

  IosFirebaseOptions({
    required this.apiKey,
    required this.appId,
    this.appGroupId,
    this.bundleId,
    this.clientId,
    this.databaseURL,
    this.deepLinkURLScheme,
    this.gaTrackingId,
    required this.messagingSenderId,
    required this.projectId,
    this.reverseClientId,
    this.storageBucket,
    this.trackingId,
    this.androidClientId,
    this.iosClientId,
  });
}

class WebFirebaseOptions implements FirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyApqlGU5-R2TfHjxGzRijPfgvzNXPJDh7I',
    appId: '1:633603071053:web:fdd9b121ff761c6a4b1004',
    messagingSenderId: '633603071053',
    projectId: 'memverse-809c7',
    databaseURL: 'https://memverse-809c7.firebaseio.com',
    storageBucket: 'memverse-809c7.firebasestorage.app',
    authDomain: 'memverse-809c7.firebaseapp.com',
  );

  @override
  final String apiKey;

  @override
  final String appId;

  @override
  final String? appGroupId;

  @override
  final String? bundleId;

  @override
  final String? clientId;

  @override
  final String? databaseURL;

  @override
  final String? deepLinkURLScheme;

  @override
  final String? gaTrackingId;

  @override
  final String messagingSenderId;

  @override
  final String projectId;

  @override
  final String? reverseClientId;

  @override
  final String? storageBucket;

  @override
  final String? trackingId;

  @override
  final String? androidClientId;

  @override
  final String? iosClientId;

  @override
  final String? authDomain;

  WebFirebaseOptions({
    required this.apiKey,
    required this.appId,
    this.appGroupId,
    this.bundleId,
    this.clientId,
    this.databaseURL,
    this.deepLinkURLScheme,
    this.gaTrackingId,
    required this.messagingSenderId,
    required this.projectId,
    this.reverseClientId,
    this.storageBucket,
    this.trackingId,
    this.androidClientId,
    this.iosClientId,
    this.authDomain,
  });
}
